### ISSUE TITLE
Possible database load issue on subsequent getStatus calls on stock model

### ISSUE THREAD

**Issue by masmrlar** [ebayenterprise-eu/magento-oms#3]
The implementation of the stock item in Ebaye_Inventory_Model_Stock may contain a database load issue in getStatus.

Due to a call to an undefined variable, the stock status collection is load on each subsequent call of the method getStatus and may cause higher database load.

    /**
     * @param  Mage_Catalog_Model_Product         $product
     * @return Ebaye_Inventory_Model_Stock_Status
     */
    public function getStatus(Mage_Catalog_Model_Product $product)
    {
        $statuses = $product->getData(self::PRODUCT_DATA_STATUSES_INDEX);
        if (!isset($items[$this->getId()])) {
            $items = $this->getStatusCollection($product->getStore()->getWebsiteId())
                ->addFieldToFilter('product_id', $product->getId())
                ->getItems();

**Comment by masmrlar** [comment]
Hi, here is the fix on this:
    /**
     * @param  Mage_Catalog_Model_Product         $product
     * @return Ebaye_Inventory_Model_Stock_Status
     */
    public function getStatus(Mage_Catalog_Model_Product $product)
    {
        $result = $product->getData(self::PRODUCT_DATA_STATUSES_INDEX);
        if (!is_array($result) || !isset($result[$this->getId()])) {
            $items = $this->getStatusCollection($product->getStore()->getWebsiteId())
                ->addFieldToFilter('product_id', $product->getId())
                ->getItems();

            $productStockStatus = reset($items);
            $result[$this->getId()] = $productStockStatus;
            $product->setData(self::PRODUCT_DATA_STATUSES_INDEX, $result);
        }

        return $result[$this->getId()];
    }

**Comment by skolodyazhnyy** [comment]
Thanks for report, I will take a look shorty

**Comment by skolodyazhnyy** [comment]
Fixed in `Build 54-41`
